### ISSUE TITLE
Train lora with image width more than 1024 px, like 960*1280

### ISSUE THREAD

**Issue by Lantianyou** [kijai/ComfyUI-FluxTrainer#11]
If you meet the following error, try change this line https://github.com/kijai/ComfyUI-FluxTrainer/blob/3c3121915fe1e49b86891d25119f13cbd6712189/library/train_util.py#L4062  from `default=1024` to `default=1280` or whatever number suitable of your dataset. It would be really helpful if we can change it from ComfyUI.

BTW, thanks @kijai , you did great work. We feel super excited to visualize the trainning process. 

![Uploading image.png…]()

**Comment by Lantianyou** [comment]
![image](https://github.com/user-attachments/assets/e282b6e1-da0e-4f1e-a101-6c40a0d7a942)

**Comment by Lantianyou** [comment]
As far as I know, there are a million training parameters stored in external config files in `sd-scripts`, it would be really convinient if  `ComfyUI-FluxTrainer` can have another node to override default value for those trainning parameters. 

Thank you again for providing such a great experience.

**Comment by Lantianyou** [comment]
By training paramters I mean like these
<img width="394" alt="image" src="https://github.com/user-attachments/assets/6b89c952-b4f0-4c44-ac80-dd2d0bb9dfbd">

**Comment by kijai** [comment]
> As far as I know, there are a million training parameters stored in external config files in `sd-scripts`, it would be really convinient if `ComfyUI-FluxTrainer` can have another node to override default value for those trainning parameters.
> 
> Thank you again for providing such a great experience.

I did actually add additional arguments input couple of days ago for this exact reason, it takes them as `--argument` format, just like from command line. For example I used it myself to enable deepspeed: 

![image](https://github.com/user-attachments/assets/7a61ae8d-325b-42e2-949a-3723662feb4b)

I will add the min and max bucket size to the dataset nodes as they do make sense there.

**Comment by Lantianyou** [comment]
> > As far as I know, there are a million training parameters stored in external config files in `sd-scripts`, it would be really convinient if `ComfyUI-FluxTrainer` can have another node to override default value for those trainning parameters.
> 
> > 
> 
> > Thank you again for providing such a great experience.
> 
> 
> 
> I did actually add additional arguments input couple of days ago for this exact reason, it takes them as `--argument` format, just like from command line. For example I used it myself to enable deepspeed: 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/7a61ae8d-325b-42e2-949a-3723662feb4b)
> 
> 
> 
> I will add the min and max bucket size to the dataset nodes as they do make sense there.
> 
> 

Thank you. Truly great work

**Comment by chaorenai** [comment]
Great feature, much needed
