### ISSUE TITLE
Prodigy optimizer and weight_decay 

### ISSUE THREAD

**Issue by bananasss00** [kijai/ComfyUI-FluxTrainer#15]
Thank you for your work. Could you please add the Prodigy config similar to how it is done for Adafactor? Here are its arguments: https://pytorch-optimizers.readthedocs.io/en/latest/optimizer/#pytorch_optimizer.Prodigy

1) Alternatively, could you add an additional text field for optimizer_args in the "Optimizer Config" node, similar to the "Init Flux LoRA Training->additional_args" node?
2) Additionally, I am interested in the weight_decay parameter. It would be great if you could add it for Adafactor and the "Optimizer Config" as well.

**Comment by kijai** [comment]
![image](https://github.com/user-attachments/assets/b5b6b87d-1a42-49ca-b0a2-88f2ab3bf51a)

This should do it? I think I should separate the lr_scheduler settings to it's own node too...

**Comment by kijai** [comment]
Actually it's not accepting those other parameters on the list, weight_decay is accepted though.
