### ISSUE TITLE
ImageConcatFromBatch node not found

### ISSUE THREAD

**Issue by ShmuelRonen** [kijai/ComfyUI-FluxTrainer#2]
After install everything got: ImageConcatFromBatch node not found

 
![not found](https://github.com/user-attachments/assets/2a10b694-7c56-4028-b82e-15ce59ca6b3f)

This is a error i got on ComfyUI log. 

[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "E:\ComfyUI_4ALL\ComfyUI\server.py", line 733, in trigger_on_prompt
    json_data = handler(json_data)
                ^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_4ALL\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 867, in prompt_handler
    if node["class_type"] == "smZ CLIPTextEncode":
       ~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'

invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#117'", 'extra_info': {}}

**Comment by kijai** [comment]
This is a new node I just added yesterday to KJNodes: https://github.com/kijai/ComfyUI-KJNodes

It's fully optional though and only used to create a final grid with the validation sampling results.
