### ISSUE TITLE
How to train more optimization steps?

### ISSUE THREAD

**Issue by enkie358** [kijai/ComfyUI-FluxTrainer#24]
Hi,

I had a quick question, I noticed that changing the number of repeats, or number of datasets the overall optimization steps appears to remain the same (3000). 

If I wanted to train a lora for longer (more overall optimization steps), what would be the best way to go about it?

**Comment by kijai** [comment]
You just increase the max_train_steps, everything is currently calculated by that.

**Comment by enkie358** [comment]
thank you!
