### ISSUE TITLE
save and resume trainining

### ISSUE THREAD

**Issue by kotaxyz** [kijai/ComfyUI-FluxTrainer#35]
i have been testing with the node and everything is working fine but i don't know if there is an option to save every certain amount of steps like save a lora every 350 step and if anything happened i can resume training from it

**Comment by RaySteve312** [comment]
> i found someone mention network_weights=path_to_lora i will give it a try

did it work? how to use the network_weights=path_to_lora ?
after I trained 1000steps, I want to change the learning rate. If I use the default  workflow, I have to restart training from the begining 0 step. Is this a way to change the learning rate and then resume training from 1000 steps?

**Comment by RaySteve312** [comment]
> @RaySteve312 Try this and if it works you can give your feedback so we know its working fine !

I'm sure now. It doesn't work at all.

**Comment by RaySteve312** [comment]
I use a wrong dir now,.

It's still training.

**Comment by RaySteve312** [comment]
Let me try --network_weights=/root/ComfyUI/

at least it identify the dir is wrong.

**Comment by RaySteve312** [comment]
Let me try --network_weights=/root/ComfyUI/

at least it identify the dir is wrong.

**Comment by RaySteve312** [comment]
It demands the same dim and alpha.
I'm a little confident now.

**Comment by RaySteve312** [comment]
It demands the same dim and alpha.
I'm a little confident now.

**Comment by RaySteve312** [comment]
the result is similar to the image from 2000 steps rather than image from 0 step.
I'm sure it works now.
Just use  --network_weights=your dir 
![屏幕截图 2024-09-07 050930](https://github.com/user-attachments/assets/27619fdb-55a0-4fb0-8f76-a6d4374547bb)
