### ISSUE TITLE
feature request - reg data set

### ISSUE THREAD

**Issue by whmc76** [kijai/ComfyUI-FluxTrainer#37]
You know, in the case of small datasets, using regularized datasets to increase the generalization and accuracy of the model, hopefully adding support for regularized training

**Comment by kijai** [comment]
This should now be possible, though I have not tested it:
![image](https://github.com/user-attachments/assets/fd5d5a9e-b452-440a-8a2f-898ac003394b)

**Comment by chy-chiu** [comment]
I have tested it and unfortunately it does not work. I have since fixed it locally, but cannot commit.

In particular, in nodes.py under `TrainDatasetAdd` I modified this method: 
`def create_config(self, dataset_config, dataset_path, class_tokens, width, height, batch_size, num_repeats, enable_bucket,  
                  bucket_no_upscale, min_bucket_reso, max_bucket_reso):
        
        reg_dir = dataset_config.get("reg_data_dir")

        subsets = [
                {
                    "image_dir": dataset_path,
                    "class_tokens": class_tokens,
                    "num_repeats": num_repeats
                },
            ]

        if reg_dir:
            try:
                reg_folder = reg_dir.split("/")[-1]

                num_repeats = int(reg_folder.split("_")[0])

                reg_subset = {"image_dir": reg_dir, "class_tokens": reg_folder.split("_")[1], "num_repeats": num_repeats, "is_reg": True}
            
                subsets.append(reg_subset)
            except Exception as e:
                logger.warning("Unable to parse regularization folder \n", e)
        

        new_dataset = {
            "resolution": (width, height),
            "batch_size": batch_size,
            "enable_bucket": enable_bucket,
            "bucket_no_upscale": bucket_no_upscale,
            "min_bucket_reso": min_bucket_reso,
            "max_bucket_reso": max_bucket_reso,
            "subsets": subsets
        }
`

**Comment by kijai** [comment]
O

> I have tested it and unfortunately it does not work. I have since fixed it locally, but cannot commit.
> 
> In particular, in nodes.py under `TrainDatasetAdd` I modified this method:
> 
> `def create_config(...):
> 
> ```
>     reg_dir = dataset_config.get("reg_data_dir")
> 
>     subsets = [
>             {
>                 "image_dir": dataset_path,
>                 "class_tokens": class_tokens,
>                 "num_repeats": num_repeats
>             },
>         ]
> 
>     if reg_dir:
>         try:
>             reg_folder = reg_dir.split("/")[-1]
> 
>             num_repeats = int(reg_folder.split("_")[0])
> 
>             reg_subset = {"image_dir": reg_dir, "class_tokens": reg_folder.split("_")[1], "num_repeats": num_repeats, "is_reg": True}
>         
>             subsets.append(reg_subset)
>         except Exception as e:
>             logger.warning("Unable to parse regularization folder \n", e)
>     
> 
>     new_dataset = {
>         "resolution": (width, height),
>         "batch_size": batch_size,
>         "enable_bucket": enable_bucket,
>         "bucket_no_upscale": bucket_no_upscale,
>         "min_bucket_reso": min_bucket_reso,
>         "max_bucket_reso": max_bucket_reso,
>         "subsets": subsets
>     }`
> ```

So it needs to be a subset that's added to any given dataset? Are the repeats and class_token supposed to be same or different from the dataset? I was thinking of doing it more like this: 
![image](https://github.com/user-attachments/assets/58da945f-c23d-4e2b-94b4-8c550ca715a9)

**Comment by RaySteve312** [comment]
> O
> 
> > I have tested it and unfortunately it does not work. I have since fixed it locally, but cannot commit.
> > In particular, in nodes.py under `TrainDatasetAdd` I modified this method:
> > `def create_config(...):
> > ```
> >     reg_dir = dataset_config.get("reg_data_dir")
> > 
> >     subsets = [
> >             {
> >                 "image_dir": dataset_path,
> >                 "class_tokens": class_tokens,
> >                 "num_repeats": num_repeats
> >             },
> >         ]
> > 
> >     if reg_dir:
> >         try:
> >             reg_folder = reg_dir.split("/")[-1]
> > 
> >             num_repeats = int(reg_folder.split("_")[0])
> > 
> >             reg_subset = {"image_dir": reg_dir, "class_tokens": reg_folder.split("_")[1], "num_repeats": num_repeats, "is_reg": True}
> >         
> >             subsets.append(reg_subset)
> >         except Exception as e:
> >             logger.warning("Unable to parse regularization folder \n", e)
> >     
> > 
> >     new_dataset = {
> >         "resolution": (width, height),
> >         "batch_size": batch_size,
> >         "enable_bucket": enable_bucket,
> >         "bucket_no_upscale": bucket_no_upscale,
> >         "min_bucket_reso": min_bucket_reso,
> >         "max_bucket_reso": max_bucket_reso,
> >         "subsets": subsets
> >     }`
> > ```
> 
> So it needs to be a subset that's added to any given dataset? Are the repeats and class_token supposed to be same or different from the dataset? I was thinking of doing it more like this: ![image](https://private-user-images.githubusercontent.com/40791699/365701323-58da945f-c23d-4e2b-94b4-8c550ca715a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzY5NTUsIm5iZiI6MTcyNTk3NjY1NSwicGF0aCI6Ii80MDc5MTY5OS8zNjU3MDEzMjMtNThkYTk0NWYtYzIzZC00ZTJiLTk0YjQtOGM1NTBjYTcxNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMjA4NDU2OTk1Y2M0MDExZDA1ZjQ5MDQzZDg2NzdkOWQzY2Y3MjZmYzc1YTlkYmJmZDc2NTdiOTIxNTg1NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lc-x2shDUYvAXqfcsLwavIPbFYC7NI4hpk2hVRheg2M)

regs only repeat one time in the whole training process.

**Comment by RaySteve312** [comment]
> O
> 
> > I have tested it and unfortunately it does not work. I have since fixed it locally, but cannot commit.
> > In particular, in nodes.py under `TrainDatasetAdd` I modified this method:
> > `def create_config(...):
> > ```
> >     reg_dir = dataset_config.get("reg_data_dir")
> > 
> >     subsets = [
> >             {
> >                 "image_dir": dataset_path,
> >                 "class_tokens": class_tokens,
> >                 "num_repeats": num_repeats
> >             },
> >         ]
> > 
> >     if reg_dir:
> >         try:
> >             reg_folder = reg_dir.split("/")[-1]
> > 
> >             num_repeats = int(reg_folder.split("_")[0])
> > 
> >             reg_subset = {"image_dir": reg_dir, "class_tokens": reg_folder.split("_")[1], "num_repeats": num_repeats, "is_reg": True}
> >         
> >             subsets.append(reg_subset)
> >         except Exception as e:
> >             logger.warning("Unable to parse regularization folder \n", e)
> >     
> > 
> >     new_dataset = {
> >         "resolution": (width, height),
> >         "batch_size": batch_size,
> >         "enable_bucket": enable_bucket,
> >         "bucket_no_upscale": bucket_no_upscale,
> >         "min_bucket_reso": min_bucket_reso,
> >         "max_bucket_reso": max_bucket_reso,
> >         "subsets": subsets
> >     }`
> > ```
> 
> So it needs to be a subset that's added to any given dataset? Are the repeats and class_token supposed to be same or different from the dataset? I was thinking of doing it more like this: ![image](https://private-user-images.githubusercontent.com/40791699/365701323-58da945f-c23d-4e2b-94b4-8c550ca715a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5Nzc3NzksIm5iZiI6MTcyNTk3NzQ3OSwicGF0aCI6Ii80MDc5MTY5OS8zNjU3MDEzMjMtNThkYTk0NWYtYzIzZC00ZTJiLTk0YjQtOGM1NTBjYTcxNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE0MTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNzZlOTU2N2I0ZWQ4YTkxYjQ4NWMzMDEwMGEwNWE0ZDgzZmMzYzA2M2M0ZTI2N2Y4MDVjOGIyYTc2Y2Q5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBQ3ncPQ6ogSPm3sWR1fpx3WI6Wd6nW_So-jQpufcRk)

the token of regs must be different from the traindata token.

**Comment by kijai** [comment]
> > O
> > > I have tested it and unfortunately it does not work. I have since fixed it locally, but cannot commit.
> > > In particular, in nodes.py under `TrainDatasetAdd` I modified this method:
> > > `def create_config(...):
> > > ```
> > >     reg_dir = dataset_config.get("reg_data_dir")
> > > 
> > >     subsets = [
> > >             {
> > >                 "image_dir": dataset_path,
> > >                 "class_tokens": class_tokens,
> > >                 "num_repeats": num_repeats
> > >             },
> > >         ]
> > > 
> > >     if reg_dir:
> > >         try:
> > >             reg_folder = reg_dir.split("/")[-1]
> > > 
> > >             num_repeats = int(reg_folder.split("_")[0])
> > > 
> > >             reg_subset = {"image_dir": reg_dir, "class_tokens": reg_folder.split("_")[1], "num_repeats": num_repeats, "is_reg": True}
> > >         
> > >             subsets.append(reg_subset)
> > >         except Exception as e:
> > >             logger.warning("Unable to parse regularization folder \n", e)
> > >     
> > > 
> > >     new_dataset = {
> > >         "resolution": (width, height),
> > >         "batch_size": batch_size,
> > >         "enable_bucket": enable_bucket,
> > >         "bucket_no_upscale": bucket_no_upscale,
> > >         "min_bucket_reso": min_bucket_reso,
> > >         "max_bucket_reso": max_bucket_reso,
> > >         "subsets": subsets
> > >     }`
> > > ```
> > 
> > 
> > So it needs to be a subset that's added to any given dataset? Are the repeats and class_token supposed to be same or different from the dataset? I was thinking of doing it more like this: ![image](https://private-user-images.githubusercontent.com/40791699/365701323-58da945f-c23d-4e2b-94b4-8c550ca715a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5Nzc3NzksIm5iZiI6MTcyNTk3NzQ3OSwicGF0aCI6Ii80MDc5MTY5OS8zNjU3MDEzMjMtNThkYTk0NWYtYzIzZC00ZTJiLTk0YjQtOGM1NTBjYTcxNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE0MTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNzZlOTU2N2I0ZWQ4YTkxYjQ4NWMzMDEwMGEwNWE0ZDgzZmMzYzA2M2M0ZTI2N2Y4MDVjOGIyYTc2Y2Q5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBQ3ncPQ6ogSPm3sWR1fpx3WI6Wd6nW_So-jQpufcRk)
> 
> the token of regs must be different from the traindata token. and in all other training tools, regs always repeat only 1 time.

Okay, well the what I showed above then should work as it allows setting those individually.

**Comment by itasky** [comment]
how can we use to add more subsets on the main dataset? not only for regularation 
can't add more than one of this subset to the TrainDataSet node :(
