### ISSUE TITLE
HOW to train concrete blocks?

### ISSUE THREAD

**Issue by Maelstrom2014** [kijai/ComfyUI-FluxTrainer#39]
with this  params like in https://github.com/ostris/ai-toolkit:
part of json config:
```
               ('network', OrderedDict([
                    ('type', 'lora'),
#                    ('linear', 16),
#                    ('linear_alpha', 16)
                    ('linear', 128),
                    ('linear_alpha', 128)

                    ('network_kwargs', OrderedDict([
                        ('only_if_contains', OrderedDict([  
                            ('transformer.single_transformer_blocks.7.proj_out'),
                            ('transformer.single_transformer_blocks.20.proj_out')
                        ])),    
                    ])),
                ])),
```

**Comment by kijai** [comment]
This is now possible, example: 
![image](https://github.com/user-attachments/assets/1cf87c0c-601a-4963-9fa9-6dfe3b7b44f8)

**Comment by predest** [comment]
Thanks for making this node, which helps a lot with my training. But I see that the layer_name is quite different than the layers documented in flux.1 json file: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/transformer/diffusion_pytorch_model.safetensors.index.json.

I understand if I want to train `transformer.single_transformer_blocks.7.proj_out`, I can rename it to `lora_unet_single_blocks_7_linear2`, but what if I want to train `transformer.single_transformer_blocks.7.norm.linear`, how to input the block_args? Is there any such mapping table?

**Comment by kijai** [comment]
> Thanks for making this node, which helps a lot with my training. But I see that the layer_name is quite different than the layers documented in flux.1 json file: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/transformer/diffusion_pytorch_model.safetensors.index.json.
> 
> I understand if I want to train `transformer.single_transformer_blocks.7.proj_out`, I can rename it to `lora_unet_single_blocks_7_linear2`, but what if I want to train `transformer.single_transformer_blocks.7.norm.linear`, how to input the block_args? Is there any such mapping table?

As kohya doesn't use diffusers format for the LoRA network, you need to look at the non-diffusers version of the model:

https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main?show_file_info=flux1-dev.safetensors

I don't know the exact mappings for each weight, besides linear2 being equilevant to proj_out.

**Comment by fanksid** [comment]
> This is now possible, example: ![image](https://private-user-images.githubusercontent.com/40791699/365465706-1cf87c0c-601a-4963-9fa9-6dfe3b7b44f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NjgxNjIsIm5iZiI6MTcyNjY2Nzg2MiwicGF0aCI6Ii80MDc5MTY5OS8zNjU0NjU3MDYtMWNmODdjMGMtNjAxYS00OTYzLTlmYTktNmRmZTNiN2I0NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEzNTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNTMwZGRiYWQzZmRjN2RmZjQwZmE3YjQwYTU5MjdmNTZhZmZkOWY3ZjgwNGM1ZWNlNTllMjZjYmYwZDc1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UY6O9RpOt9HJ2RFpLPpoe77ey4WHbO53kfIApCS3d20)

Hi, are there any explanations or test about single/double block and block_args?
