### ISSUE TITLE
processing interrupted

### ISSUE THREAD

**Issue by RaySteve312** [kijai/ComfyUI-FluxTrainer#41]
![屏幕截图 2024-09-07 014002](https://github.com/user-attachments/assets/f773f24a-0e8a-4870-bc5d-338b00343559)
It happened 2 times. 
After the flux train loop 2, the processing stops. no errors. 
In lora save directory, it only saved  flux train loop 1's lora, no flux train loop 2' lora.

**Comment by kijai** [comment]
That's weird, only time I've seen that is when you literally cancel in ComfyUI. Not much to go by if it doesn't report anything else...

**Comment by RaySteve312** [comment]
it's my bad.🤣

**Comment by tiga-dudu** [comment]
> it's my bad.🤣

What is the situation? I have also encountered this situation, and it has happened several times in a row. I guarantee that I did not do anything, and it automatically stopped.

![Image](https://github.com/user-attachments/assets/fdcc24a9-4945-47e6-aec6-a8ba4d77cfcc)
