### ISSUE TITLE
[Feature Request] Allow to specify exact epochs

### ISSUE THREAD

**Issue by Apacchi88** [kijai/ComfyUI-FluxTrainer#48]
Hi, as the title suggests. 

It will allow finer control on how training is spent between repeats vs epochs.

I want to train a specific dataset of 10 images for 60 epochs with 1 repeat for 600 total steps, but I can't specify how many epochs as it is calculated automatically.

**Comment by kijai** [comment]
Epoch means number of images * repeats, in your scenario setting 60 epochs is same as settings 600 max steps. It's just different way to specify it, nothing changes in the training itself. 

You can always specify it with `--max_train_epochs` in the additional arguments box.

**Comment by Apacchi88** [comment]
> Epoch means number of images * repeats, in your scenario setting 60 epochs is same as settings 600 max steps. It's just different way to specify it, nothing changes in the training itself.
> 
> You can always specify it with `--max_train_epochs` in the additional arguments box.

Ah okay I see now after I changed the batches to 1 it is 60 now. With a batch of 2 it was calculating at 86 epochs
