### ISSUE TITLE
Fails on restart

### ISSUE THREAD

**Issue by chrisgoringe** [kijai/ComfyUI-FluxTrainer#61]
If you use resume_args, 
```
train_network.py", line 1100, in training_loop
                             UnboundLocalError: local variable 'initial_step' referenced before assignment
```

Should `initial_step` at lines 1100 and 1101 be `self.initial_step` ?

**Comment by kijai** [comment]
Probably yeah, thanks, changed that but don't have time to test right now.

**Comment by chrisgoringe** [comment]
Looks like you fixed it :)
