### ISSUE TITLE
how to train multiple or all attn blocks 

### ISSUE THREAD

**Issue by whmc76** [kijai/ComfyUI-FluxTrainer#67]
seems only train all attn blocks is a faster way for training lora.
but it seems not work if i wrote attn here
![image](https://github.com/user-attachments/assets/c1cd272a-de7a-4556-8605-e5d7c01090f2)

**Comment by kijai** [comment]
If you are referring to what civit ai LoRAs seem to have in rapid mode, you'd select the linear1 layers of all single blocks.

**Comment by whmc76** [comment]
> If you are referring to what civit ai LoRAs seem to have in rapid mode, you'd select the linear1 layers of all single blocks.

Haha, that's exactly what I was going to do, so it looks like I need to list all the blocks line by line.
I also have a question. It seems that multiple lines need to be connected with ','. If you don't add ',' it seems that an error will be reported. I hope to get your confirmation or correction. Thank you very much.

**Comment by plugcrypt** [comment]
I made two nodes for L1 and L2 blocks that you can enable or disable, you can see here https://civitai.com/models/743615 
The github repo https://github.com/plugcrypt/CRT-Nodes
Hope that could help

**Comment by whmc76** [comment]
> I made two nodes for L1 and L2 blocks that you can enable or disable, you can see here https://civitai.com/models/743615 The github repo https://github.com/plugcrypt/CRT-Nodes Hope that could help

very cool!
