### ISSUE TITLE
Can you explain the "String Constant Multiline" Node in your workflow?

### ISSUE THREAD

**Issue by q5sys** [kijai/ComfyUI-FluxTrainer#69]
Is this related area specific to the dataset you're training with or the target you are training towards?
A lot of the fields in the workflow have tooltips if you hover over them which give more detail, but this one doesn't.
I'm not sure what it's for. 
![image](https://github.com/user-attachments/assets/ce3028a6-8c2b-4d06-b4b8-e276068f8a98)

**Comment by kijai** [comment]
> Is this related area specific to the dataset you're training with or the target you are training towards? A lot of the fields in the workflow have tooltips if you hover over them which give more detail, but this one doesn't. I'm not sure what it's for. ![image](https://private-user-images.githubusercontent.com/4654247/369526152-ce3028a6-8c2b-4d06-b4b8-e276068f8a98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTk3NTAsIm5iZiI6MTcyNjg1OTQ1MCwicGF0aCI6Ii80NjU0MjQ3LzM2OTUyNjE1Mi1jZTMwMjhhNi04YzJiLTRkMDYtYjRiOC1lMjc2MDY4ZjhhOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMTkxMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWRkZjQzNzU0NGE2OGUxMTE5YzljMmFkZTRkMzVhZDE4OGZiODg4ODQ3NDY2MWVkYjc1Zjc1ZDAwYTUxNmFkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vdTSOuIgoXRsbEzfINA6Rn1z6T0JZv6GnKiJfnTY8xc)

It's for the validation prompts for the sampling during training, it's just a standard text node so it doesn't have tooltip in it, but there's tooltip where it connects to.

**Comment by q5sys** [comment]
Ah, I didn't even think to check the tooltip for the connected node.  Thanks for the response!
