### ISSUE TITLE
Finished training cant find lora

### ISSUE THREAD

**Issue by Reefermann94** [kijai/ComfyUI-FluxTrainer#7]
I set up the thing spent 7 odd hours running while i was asleep and its done, trained well.... only thing is im not sure were to look for the lora...

**Comment by kijai** [comment]
What did you have as output_path? If you didn't change it, then look for it at the ComfyUI root folder.

**Comment by Reefermann94** [comment]
I found it... sorry to make you waste your time oh Image wizard. Thanks for the help ^__^
