### ISSUE TITLE
General question about the TrainDatasetAdd Node

### ISSUE THREAD

**Issue by BlackVortexAI** [kijai/ComfyUI-FluxTrainer#78]
There is a width, height, min_bucket_resolution and max_bucket_resolution.

Do all images in a dataset have to have the same absolute resolution and must this be set for width and height? So a separate node for each resolution? If so, what is the min and max value for?

Or must the resolution of the images be in the min and max range? What are the width and height values for?

**Comment by kijai** [comment]
The nodes simply setup datasets for kohya's automatic bucketing, you don't need to do anything to the images itself, it's all handled based on the settings. When you start training you can see summary of how it resizes the images in the console log.

The separate nodes are meant for multiresolution training, or to add different datasets. If you add same dataset 3 times with different resolution, like the example workflow, it will then train using 3 differently resized versions of the dataset.

Min and max are to further limit the bucket sizes, generally you don't need to change them.

**Comment by BlackVortexAI** [comment]
> The nodes simply setup datasets for kohya's automatic bucketing, you don't need to do anything to the images itself, it's all handled based on the settings. When you start training you can see summary of how it resizes the images in the console log.
> 
> The separate nodes are meant for multiresolution training, or to add different datasets. If you add same dataset 3 times with different resolution, like the example workflow, it will then train using 3 differently resized versions of the dataset.
> 
> Min and max are to further limit the bucket sizes, generally you don't need to change them.

thanks
