### ISSUE TITLE
the training is slower too much than use aitoolkit in all the same settings 

### ISSUE THREAD

**Issue by whmc76** [kijai/ComfyUI-FluxTrainer#81]
the same dataset and same settings
but i got 5s/it in comfyui
and it is 1.5s/it in aitoolkit
i want to know why

**Comment by kijai** [comment]
Can't really know without knowing the settings and hardware? When it comes to speed it has nothing to do with ComfyUI, but the kohya scripts it uses, ComfyUI is just used to set it up.

**Comment by kijai** [comment]
> > Can't really know without knowing the settings and hardware? When it comes to speed it has nothing to do with ComfyUI, but the kohya scripts it uses, ComfyUI is just used to set it up.如果不了解设置和硬件，就无法真正知道？说到速度，它与 ComfyUI 无关，而是它使用的 kohya 脚本，ComfyUI 只是用来设置它的。
> 
> I can understand what you mean, I just think maybe there are some parameters that are not exposed that cause such a big gap in their training, maybe this question is not suitable here, but I will update it here when I find the reason for it for other people who are equally confused to take a look. Thanks for your explanation.

All I can say is that I don't experience issues with speed, so there shouldn't be anything inherently slower. Settings can work differently as ai-toolkit is somewhat different from kohya.

The question is fine, I'd just like more information as I have no reference point to what the speed you should expect with this is. 5 s/it does sound way too slow and I have not experienced anything like that with 4090.

**Comment by plugcrypt** [comment]
Be sure to have "Split Mode" to false

**Comment by whmc76** [comment]
> > > Can't really know without knowing the settings and hardware? When it comes to speed it has nothing to do with ComfyUI, but the kohya scripts it uses, ComfyUI is just used to set it up.如果不了解设置和硬件，就无法真正知道？说到速度，它与 ComfyUI 无关，而是它使用的 kohya 脚本，ComfyUI 只是用来设置它的。
> > 
> > 
> > I can understand what you mean, I just think maybe there are some parameters that are not exposed that cause such a big gap in their training, maybe this question is not suitable here, but I will update it here when I find the reason for it for other people who are equally confused to take a look. Thanks for your explanation.
> 
> All I can say is that I don't experience issues with speed, so there shouldn't be anything inherently slower. Settings can work differently as ai-toolkit is somewhat different from kohya.我只能说我没有遇到速度问题，所以本来就不应该有任何变慢的事情。设置的工作方式可能有所不同，因为 ai-toolkit 与 kohya 有些不同。
> 
> The question is fine, I'd just like more information as I have no reference point to what the speed you should expect with this is. 5 s/it does sound way too slow and I have not experienced anything like that with 4090.这个问题很好，我只是想要更多信息，因为我没有参考点来说明您应该期望的速度是多少。5 秒/它听起来确实太慢了，我还没有遇到过 4090 这样的事情。

According to my verification, there are several points that make the training time different
Aitoolkit uses multiple resolutions for training by default, while I usually only use 1024-based resolutions on comfyui, which causes a speed difference of about 2x
The size of the image footage is particularly critical to the speed. At first, I used the short-sided 1024 logic for batch processing of the footage by default, which made the footage 1-2 times larger than the total pixels of the 1024 image, and the training time more than doubled
The adam8bit used by aitoolkit by default is also a faster option than the prodigy I use in comfyui. Of course, this has less impact than the above two points.
