### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by vallestutz** [kijai/ComfyUI-FluxTrainer#82]
Hey Kijai,

first- thank you for implementing kohya in comfyui!
This is so sick ! ! !

Unfortunately I don't get it running properly.
I have 24GB vRAM and want to train ~10* 1024x1024 images.
But after the `InitFluxLoRATraining`, when the _network_trainer_ gets passed to the first `FluxTrainLoop`, I get `torch.cuda.OutOfMemoryError`.

In another Issue thread, you mentioned to install torch 2.4 which I did but I still get the error.
Anything else I could check out, to avoid over-filling up the whole memory?

**Comment by kijai** [comment]
The default workflow should only take about 17-18GB on torch 2.4.1, so if it's more then I'd still make sure you have it updated and in the correct python environment.

**Comment by vallestutz** [comment]
I installed the newest ComfyUI version (0.2.3) with torch 2.4.1
Does work now and uses ~14GB vRAM

**Comment by vallestutz** [comment]
I installed the newest ComfyUI version (0.2.3) with torch 2.4.1
Does work now and uses ~14GB vRAM

**Comment by So6sson** [comment]
Hello both of you, I still have the same issue with torch 2.6.0 and ComfyUI 0.2.3. and I'm running the workflow on a A40 (48GB VRAM) with 11 1024x1024 images. Could you help me with this ? 
This is the parameters : 
![image](https://github.com/user-attachments/assets/4d87c3f6-4c8c-493a-a94f-ea63b57a2984)

# ComfyUI Error Report
## Error Details
- **Node Type:** FluxTrainLoop
- **Exception Type:** torch.OutOfMemoryError
- **Exception Message:** Allocation on device 
## Stack Trace

``
## System Information
- **ComfyUI Version:** v0.2.3-10-gc695c4a
- **Arguments:** /ComfyUI/main.py --listen 0.0.0.0 --port 7860
- **OS:** posix
- **Python Version:** 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.6.0.dev20241015+cu124
## Devices

- **Name:** cuda:0 NVIDIA A40 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 47622258688
  - **VRAM Free:** 33845455200
  - **Torch VRAM Total:** 14763950080
  - **Torch VRAM Free:** 2423761248


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
